KPI_TABLE = [
    {
        'fio': 'Абаева Марияна Кабкеновна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Абдирова Айгерим Кудайбергеновна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Абдрахманова Айнур Ильясовна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Ажкенова Бахыт Кенесовна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Айтуреева Лаззат Адилбаевна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Акжанова Дильмара Ануашевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Алтаев Ағаби Сабыржанұлы',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Альпеисова Ильнияз Иман-Мухаметовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Амирбекова Гулмира Курасовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Амиргалина Сауле Каскарбаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Амирова Лаззат Каирхановна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Арғынбаева Жанаргүл Оралбекқызы',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Ахмедина Кумысшаш Бижановна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',    
    },
    {
        'fio': 'Ахтай Ермекгүл Аршынбай',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Ашимова Венера Изимбергеновна дежурство',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Ашимханова Анар Умирбековна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Ағыбаева Жібек Қанатқызы',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Базарова Сулу Куралбаевна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Базгутдинова Флюра Киямовна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Баисова Акбота Каныбеккызы',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Байгабылова Дамира Каиржановна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Байдюсенова Данагуль Абаевна дежурство с 01.02.2025 г.',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Байкулова Улбосын Сапаралиевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Баймуратова Гульсум Сериковна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Батаева Ирина Петровна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Бейсенова Биляш Хамитовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Беккожина Раушан Алтаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Бөкейхан Майгүл',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Грицевич Татьяна Павловна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Губина Оксана Валерьевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Едиресова Турсынгул Кузембаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Есимсеитов Кайыргали Гусманович',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Есимсеитов Кайыргали Гусманович дежурство с 01.01.2025 г.',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Жакишова Мадина Сакеновна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Жакупова Гульмира Сапаровна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Жакупова Меруерт Салиевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Жамангарина Корлан Жигеровна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Жилгельдина Алтыншаш Каировна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Жумагулова Майра Карбаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Жунусова Перизат Сайлаубаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Жусупова Жазира Асылхановна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Жусупова Жазира Асылхановна дежурство с 01.01.2025 г.',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Жусупова Мадина Асановна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Захарова Юлия Владимировна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Ибраева Карлыгаш Курмашевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Иргебаева Шынар Казытаевна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Ирисбаева-Дусаганова Тамаша Лукмановна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Ирисбаева-Дусаганова Тамаша Лукмановна дежурство с 01.01.2025 г.',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Искакова Елена Юрьевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Кадылбекова Мейрамгуль Кадылбековна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Калдыбаева Жазира Тураровна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Калиева Нуржамал Есимжановна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Калиева Нуржамал Рахметовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Карипова Кадиша Тулеуовна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Касенова Жамал Омаровна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Касенова Жамал Омаровна дежурство с 01.01.2025 г.',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Касымбекова Айбарша Кенесовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Кемелова Жалгас Балгаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Керимбекова Тамара Умирзаховна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Керимбекова Тамара Умирзаховна дежурство с 01.01.2025 г.',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Колесниченко Елена Владимировна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Корн Валентина Викторовна дежурство санитарки с 01.01.2025 г.',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Кошикбаева Айгерим Арыстанбековна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Куанышкалиева Айнагуль Аубакировна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Кульмагамбетова Галина Андреевна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Кульмагамбетова Галина Андреевна совмещение 0,25ст. с 01.03.25г.',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Курманова Каракас Ехсановна совмещение санитарки 0.25ст с 01.01.2025',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Кусаинова Жанат Сабиткызы',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Кутжанова Ардак Аскаровна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Кыдырбаева Раушан Далабаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Кәкімжанова Ақмарал Адайқызы',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Литвиненко Елена Владимировна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Литвинова Ирина Николаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Малгаждарова Айша Сагандыковна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Манылова Ольга Николаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Мардан Жайсанбек Қуандықұлы',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Матаева Кенжесара Сейтмаганбетовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Михайлова Ирина Николаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Мусабекова Сандыгул Жетписбаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Назарова Макпал Ержановна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Несипбаева Перизат Сарсеновна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Нурболова Айнур Карбозовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Нургалиева Гаухар Толеубековна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Нургалиева Гульнара Бахытбековна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Нурмагамбетова Карлыгаш Жамбуловна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Омарова Кульнар Шахметовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Орынбаева Кундызай Авезбековна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Ратушняк Ирина Николаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Рахимжанова Гульназ Сеитрахимовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Рерих Светлана Николаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Руденко Альфида Талгатовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Сабчук Лариса Викторовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Сагиндыкова Жаннат Абдуаповна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Садвакасова Гульнара Батановна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Сайфутдинова Гульнара Ильдусовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Салимжанова Роза Рахимбековна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Салыкова Гуляим Окатаевна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Сапарбаева Дариха Калыбаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Саргужина Карлыгаш Ахболатовна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Саргужина Карлыгаш Ахболатовна дежурство',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Саргужина Карлыгаш Ахболатовна совмещение 0.25 ст с 01.02.2025 г.',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Сейтакова Дамен Балтабековна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Сейткожина Зора Смаиловна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Сердалина Диана Виллеровна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Серикбаева Кульжиян Матюшевна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Серикбаева Кульжиян Матюшевна дежурство с 01.01.2025 г.',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Сосунова Раиса Рахматулловна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Суендыкова Мархаба Жоломановна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Сулейменова Гулдана Оразовна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Сулейменова Карлыгаш Тегисовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Сулейменова Шакира Рашитовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Сухаревская Людмила Ивановна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Сыздыкова Эльмира Сайлауовна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Тасбаева Айнаш Амантаевна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Тасбаева Айнаш Амантаевна дежурство с 01.01.2025 г.',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Телтаева Асима Айдаровна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Телтаева Жулдыз Айдаровна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Токмейлова Алмагуль Тауровна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Тулебаева Улжалгас Аяшовна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Тулегенова Аружан Жанатовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Туребаева Клара Сакеновна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Туякова Рысалды Самиевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Уалиева Карлыгаш Калкайдаровна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Утебаева Хабиба Тулкибаевна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Файзулин Жанибек Алтаевич',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Фокина Ирина Кумаровна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Харина Гульнара Хамитовна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Шаймурзин Ермек Негметович',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Шалгинбаева Кайргуль Маштаевна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Шалгинбаева Кайргуль Маштаевна совмещение 0.25 ст с 01.01.2025 г.',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Шалкарова Айнагуль Ерденбаевна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Шалкарова Айнагуль Ерденбаевна совмещение 0,25 ст. с 01.03.25г.',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Шалкарова Айнагуль Ерденбаевна совмещение 0,25 ст. с 14.04.2025г.',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Шевченко Светлана Валериевна',
        'kpiSum': 15000,
        'scheduleType': 'day',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Шолпанкулова Акмарал Аукеновна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
    {
        'fio': 'Ұлан Наргиз Турсуновна',
        'kpiSum': 15000,
        'scheduleType': 'shift',
        'department': 'ОЦМК-2',
        'categoryCode': '',
    },
]